# Generated by Django 5.1.2 on 2024-11-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_user_description_user_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
