# Generated by Django 5.1.2 on 2024-11-11 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_user_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_banner',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_picture',
            new_name='banner',
        ),
    ]
