# Generated by Django 5.1.3 on 2024-11-17 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_community_banner_community_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters and numbers.', regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='community',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
