# Generated by Django 5.1.3 on 2024-11-27 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_id', models.CharField(max_length=255)),
                ('post_id', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=4000, validators=[django.core.validators.MinLengthValidator(1, 'Title must be at least 1 character long')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
